module.exports = {
	CHANGE_SELECTED_COLUMNS:"CHANGE_SELECTED_COLUMNS",
    CHANGE_VISIBILE_ROWS: "CHANGE_VISIBILE_ROWS",
    SELECT_ROW: "SELECT_ROW",
    UNSELECT_ALL_ROWS: "UNSELECT_ALL_ROWS",
    UNSELECT_ROW: "UNSELECT_ROW"
};